common: &common
  adapter: postgresql
  host: localhost

development:
  <<: *common
  database: development
  pool: 5
  timeout: 5000

test:
  <<: *common
  database: test
  pool: 5
  timeout: 5000

production:
  <<: *common
  database: production
  pool: 5
  timeout: 5000
